In [ ]:
import numpy as np

In [5]:
marks = [78,89,90,65,34]
print(marks)
print(type(marks))

[78, 89, 90, 65, 34]
<class 'list'>


In [6]:
marks_arr = np.array(marks)
print(marks_arr)
print(type(marks_arr))

[78 89 90 65 34]
<class 'numpy.ndarray'>


In [14]:
age = [45,67,12,60,1,67,56]
weight = [49,24,46,20,68,79,90]

ducks = np.array([age, weight])  ## also put [] to indicate arry before ()

# print(ducks)

# print(np.size(ducks))

# print(np.shape(ducks))

# print(np.reshape(ducks,(14,1))

# ducks = ducks.reshape(14,1)    #or
# ducks = np.reshape(ducks,(2,7))
ducks = np.reshape(ducks,(7,2)) 
# ducks = np.reshape(ducks,(14,1))   # same as line above
print(ducks)

[[45 67]
 [12 60]
 [ 1 67]
 [56 49]
 [24 46]
 [20 68]
 [79 90]]


In [8]:
six_spaced = np.linspace(1,66,6)
print(six_spaced)

[ 1. 14. 27. 40. 53. 66.]


In [9]:
empt = np.empty((0,3), dtype = int)
print(empt)

[]


In [10]:
all_noughts = np.zeros((4,7), dtype=int)       # same as above - empty array
print(all_noughts)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [11]:
fll = np.full((3,4), 0, dtype=int)     # same as above - empty array
print(fll)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [12]:
identity = np.eye(8)
print(identity)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
